Puppet

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,35 +1,84 @@
 #!/usr/bin/env bash
-#Configure Nginx so that its HTTP response contains a custom header
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Update package information
-sudo apt-get -y update
+# uncomment to see the script run in action
+#set -x
 
-# Install Nginx
-sudo apt-get install -y nginx
+echo -e "Updating and doing some minor checks...\n"
 
-# Start Nginx service
-sudo service nginx start
+function install() {
+	command -v "$1" &> /dev/null
 
-# Creating an index.html page
-echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
+	#shellchecking disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-# Configuring 301 Redirection
-if ! grep -q "location /redirect_me {" /etc/nginx/sites-enabled/default; then
-sudo sed -i '/server_name _;/a'\
-        'location \/redirect_me {'\
-            'return 301 https:\/\/github.com\/ogitau;'\
-        '}' /etc/nginx/sites-enabled/default
+install nginx #installation of nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allow nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Giving  the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
 fi
 
-if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
-# Configuring Custom 404 page
-sudo sed -i '/server_name _;/a'\
-        'error_page 404 /404.html;' /etc/nginx/sites-enabled/default
-fi
+# creating  directories if they are  not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-if ! grep -q "add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default; then
-# Configuring Custon Nginx header
-sudo sed -i '47i\        add_header X-Served-By \$hostname;' /etc/nginx/sites-enabled/default
-fi
+# create a new index
+echo "Hello World!" > /var/www/html/index.html
 
-sudo service nginx restart
+# creating new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
